[workspace]
authors = ["Justin Bois <bois@caltech.edu>"]
channels = ["conda-forge"]
name = "bebi103"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
bokeh = ">=3.7.3,<4"
click = ">=8.2.1,<9"
colorcet = ">=3.1.0,<4"
contourpy = ">=1.3.3,<2"
datashader = ">=0.18.1,<0.19"
fastparquet = ">=2024.11.0,<2025"
h5netcdf = ">=1.6.3,<2"
h5py = ">=3.14.0,<4"
holoviews = ">=1.21.0,<2"
hvplot = ">=0.11.3,<0.12"
hypothesis = ">=6.136.6,<7"
ipython = ">=9.4.0,<10"
ipywidgets = ">=8.1.7,<9"
jinja2 = ">=3.1.6,<4"
jsonschema = ">=4.25.0,<5"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.3,<4"
mypy = ">=1.17.0,<2"
netcdf4 = ">=1.7.2,<2"
numba = ">=0.61.2,<0.62"
numpy = ">=2.2.6,<3"
openpyxl = ">=3.1.5,<4"
packaging = ">=25.0,<26"
pandas = ">=2.3.1,<3"
pandoc = ">=3.7.0.2,<4"
param = ">=2.2.1,<3"
pip = ">=25.1.1,<26"
pyarrow = ">=21.0.0,<22"
pytest = ">=8.4.1,<9"
scikit-image = ">=0.25.2,<0.26"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.0,<2"
seaborn = ">=0.13.2,<0.14"
selenium = ">=4.34.2,<5"
setuptools = ">=80.9.0,<81"
statsmodels = ">=0.14.5,<0.15"
sympy = ">=1.14.0,<2"
toolz = ">=1.0.0,<2"
tqdm = ">=4.67.1,<5"
traitlets = ">=5.14.3,<6"
twine = ">=6.1.0,<7"
ujson = ">=5.10.0,<6"
xarray = ">=2025.7.1,<2026"
xlrd = ">=2.0.1,<3"
zarr = ">=3.1.0,<4"
nodejs = ">=24.4.1,<24.5"
fastexcel = ">=0.14.0,<0.15"
altair = ">=5.5.0,<6"

[pypi-dependencies]
accessible-pygments = ">=0.0.5, <0.0.6"
arviz = ">=0.22.0, <0.23"
bebi103 = ">=0.1.28, <0.2"
black = ">=25.1.0, <26"
blackcellmagic = ">=0.0.2, <0.0.3"
build = ">=1.2.2.post1, <2"
cmdstanpy = ">=1.2.5, <2"
commonmark = ">=0.9.1, <0.10"
daft-pgm = ">=0.1.4, <0.2"
great-tables = ">=0.18.0, <0.19"
h5pyd = ">=0.21.0, <0.22"
hmmlearn = ">=0.3.3, <0.4"
iqplot = ">=0.3.7, <0.4"
jupytext = ">=1.17.2, <2"
jupyter-cache = ">=1.0.1, <2"
jupyterlab = "*"
jupyter-bokeh = ">=4.0.5, <5"
jupyterlab-quarto = ">=0.3.5, <0.4"
jupyterlab-spellchecker = ">=0.8.4, <0.9"
markdown-it-py = "*"
marimo = ">=0.14.13, <0.15"
multiprocess = ">=0.70.18, <0.71"
polars = ">=1.31.0, <2"
watermark = ">=2.5.0, <3"
xarray-datatree = ">=0.0.14, <0.0.15"
xarray-einstats = ">=0.9.1, <0.10"

[tool.marimo.formatting]
line_length = 88

[tool.marimo.display]
default_width = "full"

[tool.marimo.runtime]
autorun_on_startup = false
on_cell_change = "lazy"
